"""
terraform/generator.py
========================
Generates Terraform configuration files from collected user inputs.

Key design decisions:
  - AWS region is read from the AWS_DEFAULT_REGION env var (or defaults to
    us-east-1) and written as a LITERAL string into the provider block.
    It is NEVER referenced as var.aws_region — that caused the region loop.
  - write_main_tf() accepts the list of module-declared variable names and
    ONLY passes those into the module block. Extra keys collected by the agent
    (region variants, typos, etc.) are silently dropped — no "unsupported
    argument" Terraform errors.
  - terraform.tfvars is written separately and also filtered to module vars only.
"""

import os
import re
from pathlib import Path
from datetime import datetime, timezone
from typing import Any


# Root module block name for each module type (Terraform `module "…" { for_each = … }`).
MODULE_FOR_EACH_BLOCK: dict[str, str] = {
    "ec2_instance": "ec2_instances",
    "s3_bucket": "s3_buckets",
    "rds_instance": "rds_instances",
}

# Child module output attributes to expose at root (for `terraform output -json`).
MODULE_OUTPUT_ATTRS: dict[str, list[str]] = {
    "ec2_instance": ["instance_id", "public_ip"],
}


# Variables that are provider-level, not module-level.
# They are NEVER passed into the module {} block.
PROVIDER_LEVEL_VARS = {
    "aws_region", "region", "aws_default_region", "provider_region",
}


class TerraformGenerator:
    """
    Generates Terraform HCL configuration files.

    Usage:
        gen = TerraformGenerator()
        # module_var_names = list of variable names declared in the module
        gen.write_main_tf(module_path, collected_values, output_path, module_var_names)
        gen.write_tfvars(collected_values, output_path, module_var_names)
    """

    # ─── Public API ──────────────────────────────────────────────────────────────

    def write_main_tf(
        self,
        module_path: Path,
        collected_values: dict,
        output_path: Path,
        module_var_names: list[str] = None,
    ) -> None:
        """
        Generate a root main.tf that:
          1. Configures the AWS provider with a literal region string.
          2. Calls the local module, passing only the variables it declares.

        Args:
            module_path      : Absolute path to the Terraform module directory.
            collected_values : All values gathered from the user.
            output_path      : Where to write the generated main.tf.
            module_var_names : Variable names declared in the module's variables.tf.
                               If None, all non-provider keys are passed (safe fallback).
        """
        region = self._get_region()
        rel_module_path = self._relative_path(output_path.parent, module_path)

        # Filter to only variables the module actually accepts
        module_values = self._filter_to_module(collected_values, module_var_names)

        lines = [
            "# Generated by AWS Terraform Chatbot",
            f"# Timestamp: {datetime.now(timezone.utc).isoformat()}",
            "# DO NOT EDIT MANUALLY — regenerate via chatbot",
            "",
            'terraform {',
            '  required_providers {',
            '    aws = {',
            '      source  = "hashicorp/aws"',
            '      version = "~> 5.0"',
            '    }',
            '  }',
            '}',
            "",
            'provider "aws" {',
            f'  region = "{region}"',   # ← literal string, NOT var.aws_region
            '}',
            "",
            'module "resource" {',
            f'  source = "{rel_module_path}"',
            "",
        ]

        for var_name, value in module_values.items():
            hcl_val = self._to_hcl(value)
            clean_name = var_name.strip().strip('"').strip("'")
            lines.append(f"  {clean_name:<28} = {hcl_val}")

        lines += ["}", ""]

        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text("\n".join(lines), encoding="utf-8")

    def write_workspace_from_state(
        self,
        workspace_dir: Path,
        modules_root: Path,
        state: dict,
    ) -> None:
        """
        Write root main.tf and outputs.tf from chatbot workspace state.

        Each non-empty entry in state[\"by_type\"] becomes one `module` block
        with `for_each` so multiple logical instances coexist without replacing
        unrelated resources.
        """
        workspace_dir = Path(workspace_dir)
        modules_root = Path(modules_root)
        main_path = workspace_dir / "main.tf"
        outputs_path = workspace_dir / "outputs.tf"
        region = self._get_region()

        lines = [
            "# Generated by AWS Terraform Chatbot",
            f"# Timestamp: {datetime.now(timezone.utc).isoformat()}",
            "# DO NOT EDIT MANUALLY — regenerate via chatbot",
            "",
            'terraform {',
            '  required_providers {',
            '    aws = {',
            '      source  = "hashicorp/aws"',
            '      version = "~> 5.0"',
            '    }',
            '  }',
            '}',
            "",
            'provider "aws" {',
            f'  region = "{region}"',
            '}',
            "",
        ]

        by_type = state.get("by_type") or {}
        output_blocks: list[str] = []

        for mod_type in sorted(by_type.keys()):
            instances = by_type[mod_type]
            if not instances:
                continue
            module_dir = modules_root / mod_type
            if not module_dir.is_dir():
                continue
            rel = self._relative_path(workspace_dir, module_dir)
            block = MODULE_FOR_EACH_BLOCK.get(mod_type) or f"{mod_type}_group"

            # Union of variable keys across all instances
            var_keys: set[str] = set()
            for vals in instances.values():
                if isinstance(vals, dict):
                    var_keys.update(vals.keys())
            sorted_vars = sorted(var_keys)

            lines.append(f'module "{block}" {{')
            lines.append(f'  source = "{rel}"')
            lines.append("")
            lines.append("  for_each = {")

            for tf_key in sorted(instances.keys()):
                vals = instances[tf_key]
                if not isinstance(vals, dict):
                    continue
                ks = str(tf_key)
                bare_key = bool(re.match(r"^[a-zA-Z_][a-zA-Z0-9_]*$", ks))
                key_hcl = ks if bare_key else self._to_hcl(ks)
                inner_lines = [f"    {key_hcl} = {{"]
                for vk in sorted_vars:
                    if vk not in vals:
                        continue
                    inner_lines.append(
                        f"      {vk} = {self._to_hcl(vals[vk])}"
                    )
                inner_lines.append("    }")
                lines.extend(inner_lines)

            lines.append("  }")
            lines.append("")

            for vk in sorted_vars:
                lines.append(f"  {vk:<28} = each.value.{vk}")
            lines.append("}")
            lines.append("")

            attrs = MODULE_OUTPUT_ATTRS.get(mod_type)
            if attrs:
                inner = ",\n".join(
                    f"      {a} = m.{a}" for a in attrs
                )
                output_blocks.append(
                    f'output "{block}_summary" {{\n'
                    f"  value = {{\n"
                    f"    for k, m in module.{block} : k => {{\n"
                    f"{inner}\n"
                    f"    }}\n"
                    f"  }}\n"
                    f"}}"
                )

        workspace_dir.mkdir(parents=True, exist_ok=True)
        main_path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")

        if output_blocks:
            out_text = (
                "# Generated by AWS Terraform Chatbot — module summaries\n"
                + "\n\n".join(output_blocks)
                + "\n"
            )
        else:
            out_text = (
                "# Generated by AWS Terraform Chatbot — no module outputs configured\n"
            )
        outputs_path.write_text(out_text, encoding="utf-8")

        # Root module has no variables; avoid stale tfvars breaking apply.
        tfvars_path = workspace_dir / "terraform.tfvars"
        tfvars_path.write_text(
            "# No root variables — module inputs are set in main.tf (for_each).\n",
            encoding="utf-8",
        )

    def write_tfvars(
        self,
        collected_values: dict,
        output_path: Path,
        module_var_names: list[str] = None,
    ) -> None:
        """
        Generate a terraform.tfvars containing only module-level variables.
        Provider-level keys (aws_region etc.) are excluded.
        """
        module_values = self._filter_to_module(collected_values, module_var_names)

        lines = [
            "# terraform.tfvars — Generated by AWS Terraform Chatbot",
            f"# Timestamp: {datetime.now(timezone.utc).isoformat()}",
            "",
        ]
        for var_name, value in module_values.items():
            hcl_val = self._to_hcl(value)
            clean_name = var_name.strip().strip('"').strip("'")
            lines.append(f"{clean_name:<32} = {hcl_val}")

        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text("\n".join(lines), encoding="utf-8")

    # ─── Helpers ─────────────────────────────────────────────────────────────────

    def _filter_to_module(
        self,
        collected_values: dict,
        module_var_names: list[str] = None,
    ) -> dict:
        """
        Return only the entries from collected_values that:
          a) Are not provider-level variables (aws_region, region, etc.)
          b) Are in module_var_names (if that list was supplied)
        """
        result = {}
        for key, value in collected_values.items():
            # Normalise key — strip any quotes the LLM may have embedded
            clean_key = key.strip().strip('"').strip("'").strip()
            # Drop provider-level keys
            if clean_key.lower() in PROVIDER_LEVEL_VARS:
                continue
            # If we know the module's declared vars, enforce the allow-list
            if module_var_names is not None and clean_key not in module_var_names:
                continue
            result[clean_key] = value
        return result

    def _get_region(self) -> str:
        """Read AWS region from environment, defaulting to us-east-1."""
        return (
            os.environ.get("AWS_DEFAULT_REGION")
            or os.environ.get("AWS_REGION")
            or "us-east-1"
        )

    def _to_hcl(self, value: Any) -> str:
        """Convert a Python value to its HCL literal representation."""
        if isinstance(value, bool):
            return "true" if value else "false"
        if isinstance(value, (int, float)):
            return str(value)
        if isinstance(value, list):
            items = ", ".join(f'"{v}"' for v in value)
            return f"[{items}]"
        if isinstance(value, dict):
            pairs = ", ".join(f'"{k}" = "{v}"' for k, v in value.items())
            return "{" + pairs + "}"
        escaped = str(value).replace('"', '\\"')
        return f'"{escaped}"'

    def _relative_path(self, from_dir: Path, to_path: Path) -> str:
        """Return a POSIX relative path from from_dir to to_path."""
        from_r = from_dir.resolve()
        to_r = to_path.resolve()
        try:
            return to_r.relative_to(from_r).as_posix()
        except ValueError:
            import os

            return os.path.relpath(to_r, from_r).replace(os.sep, "/")